import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Sans, Rethink_Sans } from "next/font/google";
import { cn } from "@/utils/helpers";
import { getLang } from "@/utils/selectors";
import Header from "@/components/site/Header";
import "./globals.css";
import Footer from "@/components/site/Footer/Footer";
import Hero from "@/components/site/Hero/Hero";

const instrumentSans = Instrument_Sans({
	variable: "--font-instrument-sans",
	subsets: ["latin"],
	style: ["normal", "italic"],
	weight: ["400", "700"]
});

const rethinkSans = Rethink_Sans({
	variable: "--font-rethink-sans",
	subsets: ["latin"],
	style: ["normal", "italic"],
	weight: ["400", "800"]
});

export const metadata: Metadata = {
	title: getLang("site", "title"),
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
				instrumentSans.variable,
				rethinkSans.variable
			)}
		>
			<body>
				<Header />
				<main>
					<Hero />
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
};